/* 파일 테이블 */
CREATE TABLE TBL_FILE (
    ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,  /* 문의 파일 테이블의 기본 키 */
    FILE_PATH VARCHAR2(255),    /*파일 경로*/
    FILE_SIZE VARCHAR2(255),  /*파일 크기*/
    FILE_NAME VARCHAR2(255),  /* 파일 이름 */
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FILE;