/* 문의 파일 테이블 */
CREATE TABLE TBL_INQUIRY_FILE (
    ID NUMBER CONSTRAINT PK_INQUIRY_FILE PRIMARY KEY,  /*파일 테이블의 ID를 기본 키로 사용*/
    INQUIRY_ID NUMBER NOT NULL,  /*문의 테이블과 연결되는 외래 키*/
    CONSTRAINT FK_INQUIRY_FILE_FILE FOREIGN KEY (ID)
        REFERENCES TBL_FILE(ID),
    CONSTRAINT FK_INQUIRY_FILE_INQUIRY FOREIGN KEY (INQUIRY_ID)
        REFERENCES TBL_INQUIRY(ID)
);

