/* 관리자 답글 파일 테이블 */
CREATE TABLE TBL_INQUIRY_REPLY_FILE (
    ID NUMBER CONSTRAINT PK_INQUIRY_REPLY_FILE PRIMARY KEY,  /* 답글 파일 테이블의 기본 키 */
    REPLY_ID NUMBER NOT NULL,  /* 답글 테이블과 연결되는 외래 키 */
    CONSTRAINT FK_REPLY_FILE_INQUIRY_REPLY FOREIGN KEY (REPLY_ID)
        REFERENCES TBL_INQUIRY_REPLY(ID),  /* 답글 테이블의 ID를 참조 */
    CONSTRAINT TBL_INQUIRY_REPLY_FILE_FILE FOREIGN KEY (ID)
        REFERENCES TBL_FILE(ID)  /* 파일 테이블의 ID를 참조 */
);

CREATE SEQUENCE SEQ_INQUIRY_REPLY_FILE;