/* 배달기사 희망 지역 연결 테이블 */
CREATE TABLE TBL_LIKED_AREA (
    ID NUMBER CONSTRAINT PK_LIKED_AREA PRIMARY KEY,       /* 연결의 고유 ID */
    DRIVER_ID NUMBER NOT NULL,                  /* 배달기사 ID */
    REGION_ID NUMBER NOT NULL,                  /* 지역(구) ID */
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LIKED_AREA_DRIVER FOREIGN KEY (DRIVER_ID)  /* 배달기사 테이블의 ID를 참조 */
        REFERENCES TBL_DRIVER(ID) ON DELETE CASCADE,      /* 배달기사 삭제 시 연결된 희망 지역도 삭제 */
    CONSTRAINT FK_LIKED_AREA_REGION FOREIGN KEY (REGION_ID)  /* 지역 테이블의 ID를 참조 */
        REFERENCES TBL_REGION(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_LIKED_AREA;