/* 관리자 답글 테이블 */
CREATE TABLE TBL_INQUIRY_REPLY (
    ID NUMBER CONSTRAINT PK_INQUIRY_REPLY PRIMARY KEY,  /* 답글 테이블의 기본 키 */
    INQUIRY_ID NUMBER NOT NULL,  /* 문의 테이블과의 외래 키 */
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,  /* 답글 내용 (대용량 텍스트) */
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_INQUIRY_REPLY_INQUIRY FOREIGN KEY (INQUIRY_ID)
        REFERENCES TBL_INQUIRY(ID)  /* 문의 테이블의 ID를 참조 */
);

CREATE SEQUENCE SEQ_INQUIRY_REPLY;