/* 요금제 테이블 */
CREATE TABLE TBL_PLAN (
    ID NUMBER CONSTRAINT PK_PLAN PRIMARY KEY,  /* 요금제 테이블의 기본 키 */
    PLAN_GRADE VARCHAR2(100) NOT NULL,  /* 요금제 등급 */
    PLAN_PRICE NUMBER(10, 2) NOT NULL,  /* 요금제 가격 */
    PLAN_BOX_SIZE VARCHAR2(50),  /* 상자 사이즈 (예: 소형, 중형, 대형 등) */
    PLAN_MAX_MEMBERS NUMBER NOT NULL,  /* 요금제에 포함된 최대 인원수 */
    PLAN_STATUS VARCHAR2(100) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_PLAN;

SELECT * FROM TBL_PLAN;