/* 회원 테이블 */
CREATE TABLE TBL_MEMBER (
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,  /* 회원 테이블의 기본 키 */
    MEMBER_NAME VARCHAR2(100) NOT NULL,  /* 회원 이름 */
    MEMBER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,  /* 회원 이메일 (고유) */
    MEMBER_ADDRESS_CODE VARCHAR2(255) NOT NULL, /*우편번호*/
    MEMBER_ADDRESS_BASIC VARCHAR2(255) NOT NULL,  /* 기본 주소 */
    MEMBER_ADDRESS_DETAIL VARCHAR2(255) NOT NULL, /*상세 주소*/
    MEMBER_PHONE_NUMBER VARCHAR2(15) NOT NULL,  /* 회원 전화번호 */
    MEMBER_STATUS VARCHAR2(15) NOT NULL,  /* 회원 상태 (예: 활동중, 탈퇴함) */
    MEMBER_PASSWORD VARCHAR2(100) NOT NULL, /* 회원 비밀번호 */
    MEMBER_TYPE VARCHAR2(255) DEFAULT '일반' NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE, /* 회원 가입 날짜 */
    UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_MEMBER;

SELECT * FROM TBL_MEMBER;
<<<<<<< HEAD



=======
>>>>>>> b0923
