/* 회원 테이블 */
CREATE TABLE TBL_MEMBER (
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,  /* 회원 테이블의 기본 키 */
    MEMBER_NAME VARCHAR2(100) NOT NULL,  /* 회원 이름 */
    MEMBER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,  /* 회원 이메일 (고유) */
    MEMBER_ADDRESS VARCHAR2(255) NOT NULL,  /* 회원 주소 */
    MEMBER_PHONE_NUMBER VARCHAR2(15) NOT NULL,  /* 회원 전화번호 */
    MEMBER_STATUS VARCHAR2(15) NOT NULL,  /* 회원 상태 (예: 활동중, 탈퇴함) */
    MEMBER_PASSWORD VARCHAR2(100) NOT NULL, /* 회원 비밀번호 */
    CREATED_DATE DATE DEFAULT SYSDATE, /* 회원 가입 날짜 */
    UPDATED_DATE DATE DEFAULT SYSDATE
);
SELECT * FROM TBL_MEMBER;
INSERT INTO TBL_MEMBER (ID, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_STATUS, MEMBER_PASSWORD)
VALUES (1, '길동', 'TEST@GMAIL.COM', '서울시 강남구', '010-1234-5678', '활동중', 'password123');

CREATE SEQUENCE SEQ_MEMBER;