/* 배달기사 테이블 */
CREATE TABLE TBL_DRIVER (
    ID NUMBER CONSTRAINT PK_DRIVER PRIMARY KEY,  /* 배달기사 테이블의 기본 키 */
    DRIVER_BANK VARCHAR2(20) NOT NULL,  /* 배달기사 은행 */
    DRIVER_BANK_ACCOUNT VARCHAR2(20) NOT NULL,  /* 배달기사 계좌 번호 */
    CREATED_DATE DATE DEFAULT SYSDATE,  /* 배달기사 등록 날짜 */
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DRIVER_MEMBER FOREIGN KEY (ID)
<<<<<<< HEAD
    REFERENCES TBL_MEMBER(ID)  /* 회원 테이블의 ID를 pk로 사용 */
=======
    REFERENCES TBL_MEMBER(ID)  /* 회원 테이블의 ID를 참조 */
>>>>>>> 91fb0b735e504eda3c078515bea5988dcd426d3e
);

CREATE SEQUENCE SEQ_DRIVER;
SELECT * FROM TBL_DRIVER;

<<<<<<< HEAD


=======
>>>>>>> 91fb0b735e504eda3c078515bea5988dcd426d3e
