/* 구독료 결제 테이블 */
CREATE TABLE TBL_PAYMENT (
    ID NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,  /* 구독료 결제 테이블의 기본 키 */
    MEMBER_ID NUMBER NOT NULL,  /* 회원 ID */
    PLAN_ID NUMBER NOT NULL,  /* 요금제 ID */
    PAYMENT_PRICE NUMBER(10, 2) NOT NULL,  /* 결제 금액 */
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,  /* 결제 상태 (성공, 실패, 대기 등) */
    CREATED_DATE DATE DEFAULT SYSDATE, /* 결제 날짜 */
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PAYMENT_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES TBL_MEMBER(ID),  /* 회원 테이블의 ID를 참조 */
    CONSTRAINT FK_PAYMENT_PLAN FOREIGN KEY (PLAN_ID)
        REFERENCES TBL_PLAN(ID)  /* 요금제 테이블의 ID를 참조 */
);

CREATE SEQUENCE SEQ_PAYMENT;