/* 수거 테이블 */
CREATE TABLE TBL_PICKUP (
    ID NUMBER CONSTRAINT PK_PICKUP PRIMARY KEY,  /* 수거 테이블의 기본 키 */
    MEMBER_ID NUMBER NOT NULL,  /* 회원 ID */
    DRIVER_ID NUMBER,  /* 배달기사 ID */
    PICKUP_NUMBER VARCHAR2(255) NOT NULL,  /* 수거 요청 번호 */
    PICKUP_SCHEDULE VARCHAR2(255),  /* 수거 일정 */
    PICKUP_ENTER VARCHAR2(255),  /* 출입방법 */
    PICKUP_REQUEST_CONTENT VARCHAR2(1000),  /* 요청사항 내용 (대용량 텍스트) */
    PICKUP_STATUS VARCHAR2(255),  /* 수거 상태 (예: 요청, 예정, 완료) */
    CREATED_DATE DATE DEFAULT SYSDATE,/* 수거 신청 날짜 */
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PICKUP_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES TBL_MEMBER(ID),  /* 회원 테이블의 ID를 참조 */
    CONSTRAINT FK_PICKUP_DRIVER FOREIGN KEY (DRIVER_ID)
        REFERENCES TBL_DRIVER(ID)  /* 배달기사 테이블의 ID를 참조 */
);
CREATE SEQUENCE SEQ_PICKUP;

SELECT * FROM TBL_PICKUP;

SELECT R, P2.ID, P2.MEMBER_ID, P2.DRIVER_ID, P2.PICKUP_NUMBER, P2.PICKUP_SCHEDULE, P2.PICKUP_ENTER,
       P2.PICKUP_REQUEST_CONTENT, P2.PICKUP_STATUS, P2.CREATED_DATE, P2.UPDATED_DATE
FROM (
         SELECT ROWNUM R, P1.*
         FROM (
                  SELECT P.ID, P.MEMBER_ID, P.DRIVER_ID, P.PICKUP_NUMBER, P.PICKUP_SCHEDULE, P.PICKUP_ENTER,
                         P.PICKUP_REQUEST_CONTENT, P.PICKUP_STATUS, P.CREATED_DATE, P.UPDATED_DATE,
                         M.MEMBER_ADDRESS_CODE, M.MEMBER_ADDRESS_BASIC, M.MEMBER_ADDRESS_DETAIL,
                         PL.PLAN_PRICE, PL.PLAN_GRADE
                  FROM TBL_PICKUP P
                           JOIN TBL_MEMBER M ON M.ID = P.MEMBER_ID
                           JOIN TBL_PAYMENT PA ON M.ID = PA.MEMBER_ID
                           JOIN TBL_PLAN PL ON PA.PLAN_ID = PL.ID
                  ORDER BY PL.PLAN_PRICE DESC
              ) P1
         WHERE ROWNUM <= 36
     ) P2
ORDER BY P2.PLAN_PRICE DESC;





